export const FETCH_WEATHER_DATA_LOADING = 'FETCH_WEATHER_DATA_LOADING'

export const FETCH_WEATHER_DATA_SUCCESS = 'FETCH_WEATHER_DATA_SUCCESS'

export const FETCH_WEATHER_DATA_ERROR = 'FETCH_WEATHER_DATA_ERROR'
