export const FETCH_WEATHER_DATA_LOADING = 'FETCH_WEATHER_DATA_LOADING'

export const FETCH_WEATHER_DATA_SUCCESS = 'FETCH_WEATHER_DATA_SUCCESS'

export const FETCH_WEATHER_DATA_ERROR = 'FETCH_WEATHER_DATA_ERROR'

export const FETCH_TRIGGERS_LOADING = 'FETCH_TRIGGERS_LOADING'

export const FETCH_TRIGGERS_SUCCESS = 'FETCH_TRIGGERS_SUCCESS'

export const FETCH_TRIGGERS_ERROR = 'FETCH_TRIGGERS_ERROR'

export const FETCH_ACTIONS_LOADING = 'FETCH_ACTIONS_LOADING'

export const FETCH_ACTIONS_SUCCESS = 'FETCH_ACTIONS_SUCCESS'

export const FETCH_ACTIONS_ERROR = 'FETCH_ACTIONS_ERROR'
